# --- PDF Generation ---
class SkillMatchPDF(FPDF):
    def header(self):
        self.set_font("Arial", 'B', 14)
        self.cell(0, 10, "SkillMatch Resume Analysis Report", ln=True, align="C")
    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", 'I', 8)
        self.cell(0, 10, "Generated by SkillMatch", align="C")
    def add_summary(self, name, score, jobs, missing_skills, recommendations):
        self.set_font("Arial", '', 12)
        self.ln(10)
        self.cell(0, 10, f"Candidate Name: {name}", ln=True)
        self.cell(0, 10, f"Overall Resume Score: {score}%", ln=True)
        self.ln(5)
        self.set_font("Arial", 'B', 12)
        self.cell(0, 10, "Top Matching Jobs:", ln=True)
        self.set_font("Arial", '', 12)
        for job in jobs:
            self.cell(0, 10, f"- {job}", ln=True)
        self.ln(5)
        self.set_font("Arial", 'B', 12)
        self.cell(0, 10, "Top Missing Skills:", ln=True)
        self.set_font("Arial", '', 12)
        if missing_skills:
            self.multi_cell(0, 10, ", ".join(missing_skills))
        else:
            self.cell(0, 10, "None", ln=True)
        self.ln(5)
        self.set_font("Arial", 'B', 12)
        self.cell(0, 10, "Recommendations:", ln=True)
        self.set_font("Arial", '', 12)
        for tip in recommendations:
            self.multi_cell(0, 10, f"- {tip}")

# ✅ Extract name from resume and create PDF
extracted_name = extract_name(resume_text)
pdf = SkillMatchPDF()
pdf.add_page()
pdf.add_summary(
    name=extracted_name,
    score=round(avg_score, 1),
    jobs=[f"{row['Job']} ({row['Match %']}%)" for _, row in df.head(3).iterrows()],
    missing_skills=list(set(all_missing_skills))[:5],
    recommendations=[f"Learn {s}" for s in list(set(all_missing_skills))[:5]]
)
output = BytesIO()
pdf_bytes = pdf.output(dest='S').encode('latin-1')
output.write(pdf_bytes)
output.seek(0)
st.download_button(
    label="📄 Download PDF Summary",
    data=output.read(),
    file_name="SkillMatch_Report.pdf",
    mime="application/pdf"
)
